# Generated by Django 5.1.15 on 2026-09-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="boot_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="host",
            name="disk_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="host",
            name="disk_total_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="host",
            name="disk_used_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="host",
            name="net_bytes_recv",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="host",
            name="net_bytes_sent",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="host",
            name="net_recv_bps",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="host",
            name="net_sent_bps",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="disk_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="net_recv_bps",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="net_sent_bps",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
